name: calendar_views
version: 0.5.2

description: Collection of customisable calendar related widgets for Flutter.

author: ZedTheLed<zedtheled@gmail.com>

homepage: https://github.com/ZedTheLed/calendar_views
documentation:

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.5
  quiver: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.0.0 <3.0.0'
